### ISSUE TITLE
Is this possible to connect to 3rd party IMU hardware？

### ISSUE THREAD

**Issue by cxq200300** [xioTechnologies/NGIMU-Software-Public#5]
It's possible to share the communication format that allow this to talk to 3rd party hardware？

**Comment by xioTechnologies** [comment]
I suggest you instead use the [x-IMU3 GUI](https://github.com/xioTechnologies/x-IMU3-Software) for this.  The x-IMU3 supports an ASCII format and so would be much easier to emulate.  The x-IMU3 communication protocol is described in detail in the user manual.

**Comment by cxq200300** [comment]
> I suggest you instead use the [x-IMU3 GUI](https://github.com/xioTechnologies/x-IMU3-Software) for this. The x-IMU3 supports an ASCII format and so would be much easier to emulate. The x-IMU3 communication protocol is described in detail in the user manual.

Thanks, I would try this.
